name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >
          --health-cmd="mongo --eval 'db.adminCommand(\"ping\")'"
          --health-interval=10s
          --health-timeout=10s
          --health-retries=5

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Checking Docker version
        run: |
          docker version --format '{{.Server.APIVersion}}'
          docker version --format '{{.Client.APIVersion}}'

      - name: Clean up resources from previous jobs
        run: docker system prune -af

      - name: Create local container network
        run: docker network create github_network || true

      - name: Start MongoDB service container
        run: |
          docker pull mongo:5.0
          docker create \
            --name mongodb \
            --label mongodb \
            --network github_network \
            --network-alias mongodb \
            -p 27017:27017 \
            --health-cmd="mongo --eval 'db.adminCommand(\"ping\")'" \
            --health-interval=10s \
            --health-timeout=10s \
            --health-retries=5 \
            -e GITHUB_ACTIONS=true \
            -e CI=true \
            mongo:5.0

      - name: Wait for MongoDB to start
        run: |
          for i in {1..30}; do
            docker exec mongodb mongo --eval 'db.adminCommand("ping")' && break || sleep 2
          done

      - name: Install dependencies
        run: |
          npm install

      - name: Run tests
        run: |
          npm test

      - name: Build the application
        run: |
          npm run build